app/news/models.py
from sqlalchemy import Column, Integer, ForeignKey
from sqlalchemy.orm import relationship

from app.database import db

def dump_datetime(value):
    """Deserialize datetime object into string form for JSON processing."""
    if value is None:
        return None
    return [value.strftime("%Y-%m-%d"), value.strftime("%H:%M:%S")]

class News(db.Model):
    __tablename__ = 'news'

    id = db.Column(db.Integer, primary_key=True)
    link = db.Column(db.String(5000), nullable=False)
    save_date = db.Column(db.DateTime(timezone=True), nullable=False)
    pub_date = db.Column(db.DateTime(timezone=True), nullable=False)
    title = db.Column(db.String(5000), nullable=False)
    content = db.Column(db.Text)
    news_source_parent_fk = Column(Integer, ForeignKey('news_source.id'), nullable=False)
    source = relationship("NewsSource")

    def __repr__(self):
        return self.name

    @property
    def serialize(self):
        return {
            'id': self.id,
            'link': self.link,
            'saved': dump_datetime(self.save_date),
            'published': dump_datetime(self.pub_date),
            'title': self.title,
            'content': self.content,
            'source': self.source.serialize
        }


class NewsSource(db.Model):
    __tablename__ = "news_source"

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(5000), nullable=False)
    url = db.Column(db.String(5000), nullable=False)

    @property
    def serialize(self):
        return {
            'id': self.id,
            'name': self.name,
            'link': self.url
        }

app/news/controllers.py
from flask import (
    Blueprint,
    render_template,
    flash,
    abort,
    request,
    current_app,
    session,
    make_response,
    redirect,
    jsonify
)
from json import (
    dumps,
    loads
)
from sqlalchemy.exc import SQLAlchemyError

from .models import News

module = Blueprint('news', __name__)


def log_error(*args, **kwargs):
    current_app.logger.error(*args, **kwargs)


NEWS_PER_PAGE = 'news-per-page'
DEFAULT_NEWS_PER_PAGE = 10
RANGE_NEWS_PER_PAGE = list(range(1, 101))

NEWS_FILTER = 'news-filter'
DEFAULT_FILTER = ''
MIN_FILTER = 3

PAGE = "page"


@module.route('/news/', methods=['GET'])
@module.route('/news/page/<int:page>/', methods=['GET'])
def index(page=1):
    return render_template('news/index.html', object_list=__load__(True, page), filter=__filter__(),
                           per_page=__per_page__())


@module.route('/news/csv_dump', methods=['GET'])
def csv_dump():
    sp = '\t'

    def row(news):
        return news.pub_date.strftime("%d.%m.%Y") + sp + news.source.name.replace('\n', ' ') + sp + news.title.replace('\n', ' ')

    title = 'publication date' + sp + 'source' + sp + 'title' + '\n'
    txt = title + '\n'.join(map(row, __load__(False)))
    response = make_response(txt)
    response.headers['Content-Disposition'] = "attachment; filename=news.csv"
    return response


@module.route('/news/json_dump', methods=['GET'])
def json_dump():
    def f(n):
        return n.serialize
    jnews = dumps(__load__(False), default=f)
    response = make_response(jnews)
    response.headers['Content-Disposition'] = "attachment; filename=news.json"
    return response


@module.route('/news/set_filter', methods=['POST'])
def set_filter():
    f = request.form[NEWS_FILTER]
    session[NEWS_FILTER] = f if len(f) > MIN_FILTER else DEFAULT_FILTER
    return redirect("/news/", code=302)



@module.route('/news/set_per_page', methods=['POST'])
def set_per_page():
    try:
        f = int(request.form[NEWS_PER_PAGE])
        if f in RANGE_NEWS_PER_PAGE:
            session[NEWS_PER_PAGE] = f
    except ValueError:
        log_error('non-integer sent to /news/set_per_page')
    return redirect("/news/", code=302)


def __filter__():
    return session[NEWS_FILTER] if session.has_key(NEWS_FILTER) else DEFAULT_FILTER


def __per_page__():
    return session[NEWS_PER_PAGE] if session.has_key(NEWS_PER_PAGE) else DEFAULT_NEWS_PER_PAGE


def __load__(paginate, page=0):
    news = None

    def paginated_filter():
        return News.query.filter(News.title.contains(session[NEWS_FILTER])) \
            .order_by(News.pub_date.desc()).paginate(page, per_page=__per_page__(), error_out=True)

    def paginated_nofilter():
        return News.query.order_by(News.pub_date.desc()).paginate(page, per_page=__per_page__(), error_out=True)

    def nopanated_filter():
        return News.query.filter(News.title.contains(session[NEWS_FILTER])).order_by(News.pub_date).all()

    try:
        if not paginate and session.has_key(NEWS_FILTER):
            news = nopanated_filter()
        else:
            news = paginated_filter() if session.has_key(NEWS_FILTER) else paginated_nofilter()
    except SQLAlchemyError as e:
        log_error('Error while querying database', exc_info=e)
        flash('There was uncaught database query', 'danger')
        abort(500)
    return news

app/templates/news/index.html
{% extends "base.html" %}
{% set active_page = "news" %}

{% block meta_title %} News aggregation {% endblock %}

{% block meta_descr %} News aggregation {% endblock %}


{% block content %}

    {% if object_list.items %}
        {% for news in object_list.items %}
            <div class="blog-post">
                <div class="blog-post-content">
                    <p><b>{{ news.pub_date.strftime('%H:%M %d.%m.%Y') }}:</b> {{ news.title }}</p>
                    <a href="{{ news.link }}" target="_blank" type="button" class="btn btn-default"
                       data-toggle="tooltip"
                       data-placement="bottom"><span class="glyphicon glyphicon-link" aria-hidden="true"></span>
                        Original</a>
                    {% if news.content %}
                        <button type="button" class="btn btn-default" position="bottom" data-toggle="popover"
                                title="saved {{ news.save_date.strftime('%H:%M (GMT) %d.%m.%Y') }}"
                                data-content="{{ news.content }}">
                            <span class="glyphicon glyphicon-paperclip" aria-hidden="true"></span> Show saved
                        </button>
                    {% endif %}
                    <a href="{{ news.source.url }}" target="_blank" type="button" class="btn btn-default"
                       data-toggle="tooltip"
                       data-placement="bottom">
                        <span class="glyphicon glyphicon-magnet" aria-hidden="true"></span> {{ news.source.name }}</a>
                </div>
            </div>
        {% endfor %}
    {% else %}
        <div class="alert alert-info">There is no news yet. Is crawler online?</div>
    {% endif %}

{% endblock %}

{% block sidebar_add %}
    <form action="{{ url_for('news.set_filter') }}" method="post">
        <div class="input-group">
            <fieldset>
                <input name="news-filter" type="text" placeholder="filter" class="form-control" value="{{ filter }}">
            </fieldset>
            <span class="input-group-btn">
                <button class="btn" type="submit" style="margin-left: 2px">Apply</button>
            </span>
        </div>
    </form>
    <form action="{{ url_for('news.set_per_page') }}" method="post">
        <div class="input-group">
            <fieldset>
                <select class="form-control" name="news-per-page">
                    <option id="news-per-page-1" value=1>1 per page</option>
                    <option id="news-per-page-5" value=5>5 per page</option>
                    <option id="news-per-page-10" value=10>10 per page</option>
                    <option id="news-per-page-20" value=20>25 per page</option>
                    <option id="news-per-page-50" value=50>50 per page</option>
                    <option id="news-per-page-100" value=100>100 per page</option>
                </select>
            </fieldset>
            <span class="input-group-btn">
                <button class="btn" type="submit" style="margin-left: 2px">Apply</button>
            </span>
        </div>
    </form>
    <a href="{{ url_for('news.csv_dump') }}" target="_blank" type="button" class="btn btn-default">
                        <span class="glyphicon glyphicon-download" aria-hidden="true"></span> .csv</a>
    <a href="{{ url_for('news.json_dump') }}" target="_blank" type="button" class="btn btn-default">
                        <span class="glyphicon glyphicon-download" aria-hidden="true"></span>json</a>
{% endblock %}

{% block pagination %}
    {% import "pagination.html" as pagination_macros %}
    {{ pagination_macros.render_pagination(object_list, 'news.index') }}
{% endblock pagination %}


{% block extra_js %}
    <script>
        $("[data-toggle=popover]").popover({html: true});
        document.getElementById("news-per-page-{{ per_page }}").setAttribute("selected", true);
    </script>
{% endblock %}