app/monitoring/controllers.py
from flask import (
    Blueprint,
    render_template,
    flash,
    abort,
    current_app
)

from sqlalchemy.exc import SQLAlchemyError
from app.database import db

import os
import socket

from .models import ServiceState, ServiceTarget, OttdStatus

import memcache

module = Blueprint('monitoring', __name__)

CACHE_TTL = 20

mc = memcache.Client([os.environ['MEMCACHED_ADDRESS']], debug=0)


def log_error(*args, **kwargs):
    current_app.logger.error(*args, **kwargs)


@module.route('/mon/', methods=['GET'])
def index():
    return render_template('monitoring/index.html', object_list=check_targets())


def check_targets():
    data = None
    try:
        data = __service_data__()
        data.extend(__ottd_data__())
    except SQLAlchemyError as e:
        log_error('Error while querying database', exc_info=e)
        flash('There was uncaught database query', 'danger')
        abort(500)
    return data


def __service_data__():
    return list(map(__check_service__, ServiceTarget.query.all()))


def __ottd_data__():
    heads = db.engine.execute(
        "SELECT DISTINCT ON (ottd_source) id, probe_date, ottd_source FROM   ottd_status ORDER  BY ottd_source, probe_date DESC, id;")
    headIds = []
    for head in heads:
        headIds.append(head[0])
    for id in headIds: print(id)
    return list(map(__format_ottd__, OttdStatus.query.filter(OttdStatus.id.in_(headIds)).all()))


def __format_ottd__(st):
    info = "Clients: {0} Companies: {1} Year: {2}".format(st.players_online, st.companies_online, st.game_date) if st.online else ""
    return ServiceState(name="OpenTTD", info=info, state=st.online, comment=st.source.name)


def __check_service__(service_target):
    def __check_port__():
        sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        result = sock.connect_ex((service_target.host, service_target.port))
        state = True if result == 0 else False
        return ServiceState(name=service_target.name, state=state)

    key = str(hash(service_target.name))
    service_state = mc.get(key)
    if not service_state:
        if isinstance(service_target, ServiceTarget):
            service_state = __check_port__()
            mc.set(key, service_state, CACHE_TTL)
    return service_state

app/news/controllers.py
from flask import (
    Blueprint,
    render_template,
    flash,
    abort,
    request,
    current_app,
    session,
    make_response,
    redirect,
    jsonify
)
from json import (
    dumps,
    loads
)
from sqlalchemy.exc import SQLAlchemyError

from .models import News

module = Blueprint('news', __name__)


def log_error(*args, **kwargs):
    current_app.logger.error(*args, **kwargs)


NEWS_PER_PAGE = 'news-per-page'
DEFAULT_NEWS_PER_PAGE = 10
RANGE_NEWS_PER_PAGE = list(range(1, 101))

NEWS_FILTER = 'news-filter'
DEFAULT_FILTER = ''
MIN_FILTER = 3

PAGE = "page"


@module.route('/news/', methods=['GET'])
@module.route('/news/page/<int:page>/', methods=['GET'])
def index(page=1):
    return render_template('news/index.html', object_list=__load__(True, page), filter=__filter__(),
                           per_page=__per_page__())


@module.route('/news/csv_dump', methods=['GET'])
def csv_dump():
    sp = '\t'

    def row(news):
        return news.pub_date.strftime("%d.%m.%Y") + sp + news.source.name.replace('\n', ' ') + sp + news.title.replace('\n', ' ')

    title = 'publication date' + sp + 'source' + sp + 'title' + '\n'
    txt = title + '\n'.join(map(row, __load__(False)))
    response = make_response(txt)
    response.headers['Content-Disposition'] = "attachment; filename=news.csv"
    return response


@module.route('/news/json_dump', methods=['GET'])
def json_dump():
    def f(n):
        return n.serialize
    jnews = dumps(__load__(False), default=f)
    response = make_response(jnews)
    response.headers['Content-Disposition'] = "attachment; filename=news.json"
    return response


@module.route('/news/set_filter', methods=['POST'])
def set_filter():
    f = request.form[NEWS_FILTER]
    session[NEWS_FILTER] = f if len(f) > MIN_FILTER else DEFAULT_FILTER
    return redirect("/news/", code=302)



@module.route('/news/set_per_page', methods=['POST'])
def set_per_page():
    try:
        f = int(request.form[NEWS_PER_PAGE])
        if f in RANGE_NEWS_PER_PAGE:
            session[NEWS_PER_PAGE] = f
    except ValueError:
        log_error('non-integer sent to /news/set_per_page')
    return redirect("/news/", code=302)


def __filter__():
    return session[NEWS_FILTER] if session.has_key(NEWS_FILTER) else DEFAULT_FILTER


def __per_page__():
    return session[NEWS_PER_PAGE] if session.has_key(NEWS_PER_PAGE) else DEFAULT_NEWS_PER_PAGE


def __load__(paginate, page=0):
    news = None

    def paginated_filter():
        return News.query.filter(News.title.contains(session[NEWS_FILTER])) \
            .order_by(News.pub_date.desc()).paginate(page, per_page=__per_page__(), error_out=True)

    def paginated_nofilter():
        return News.query.order_by(News.pub_date.desc()).paginate(page, per_page=__per_page__(), error_out=True)

    def nopanated_filter():
        return News.query.filter(News.title.contains(session[NEWS_FILTER])).order_by(News.pub_date).all()

    try:
        if not paginate and session.has_key(NEWS_FILTER):
            news = nopanated_filter()
        else:
            news = paginated_filter() if session.has_key(NEWS_FILTER) else paginated_nofilter()
    except SQLAlchemyError as e:
        log_error('Error while querying database', exc_info=e)
        flash('There was uncaught database query', 'danger')
        abort(500)
    return news

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="{{ url_for('static', filename='img/favicon.ico') }}">

    <title>{% block meta_title %}{% endblock meta_title %}</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css"
          integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

    <!-- Custom styles for this template -->
    <link href="{{ url_for('static', filename='css/styles.css') }}" rel="stylesheet">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->
</head>

<body>

<div class="blog-masthead">
    <div class="container">
        <nav class="blog-nav">
            <a id="news" class="blog-nav-item" href="{{ url_for('news.index') }}">Home</a>
            <a id="monitoring" class="blog-nav-item" href="{{ url_for('monitoring.index') }}">Monitoring</a>
        </nav>
    </div>
</div>

{% block pre_container %}
    <div class="container">

        <div class="blog-header">
            <h1 class="blog-title">e-ch hpg</h1>
            <p class="lead blog-description">
                {% block meta_descr %}
                {% endblock %}
            </p>
        </div>

        <div class="row">

            {% block pre_content %}
                <div class="col-sm-8 blog-main">

                    {% include "messages.html" %}

                    {% block content %}
                    {% endblock %}

                </div><!-- /.blog-main -->
            {% endblock pre_content %}

            {% block pre_sidebar %}
                <div class="col-sm-3 col-sm-offset-1 blog-sidebar">
                    <div class="sidebar-module">
                        {% block sidebar_add %}
                        {% endblock %}
                    </div>
                    <div class="sidebar-module sidebar-module-inset">
                        <h4>About</h4>
                        <p>Welcome to Eugene Č. homepage. It's my pet project for news listing and service availability monitoring.</p>
                        <p>UI is written in Python, Flask, Blueprints.<br/>Backend: Scala + SkalikeJDBC, Akka</p>
                        <p><a href="https://bitbucket.org/euch/flask-e">Source code</a></p>
                        <p>Crawler <a href="https://bitbucket.org/euch/crawl-e">source code</a></p>
                        <p><a href="http://netda.ddns.net:8080">Old Homepage</a></p>
                    </div>
                    <div class="sidebar-module">
                        <h4>/me elsewhere</h4>
                        <ol class="list-unstyled">
                            <li><a href="https://bitbucket.org/euch">BitBucket</a></li>
                            <li><a href="https://twitter.com/eu_ch">Twitter</a></li>
                        </ol>
                    </div>
                </div><!-- /.blog-sidebar -->
            {% endblock pre_sidebar %}

            {% block pagination %}
            {% endblock pagination %}

        </div><!-- /.row -->


    </div><!-- /.container -->
{% endblock pre_container %}

<footer class="blog-footer">
    <p>
        <script type="text/javascript">
            var since_year = 2015;
            var cur_year = new Date().getFullYear();
            var cpr = " © <a href=\"https://twitter.com/eu_ch\">@eu_ch</a>";
            if (since_year === cur_year) {
                document.write(since_year + cpr);
            } else {
                document.write(since_year + " - " + cur_year + cpr);
            }
        </script>
    </p>
    <p>Based on <a href="https://twitter.com/mdo">@mdo</a> source code.</p>
    <p>All trademarks, service marks, trade names, trade dress, product names and logos appearing on the site are the property of their respective owners.</p>
    <p>
        <a href="#">Back to top</a>
    </p>
</footer>


<!-- Bootstrap core JavaScript
================================================== -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"
        integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS"
        crossorigin="anonymous"></script>

{#{% set active_page = active_page|default('monitoring') -%}#}
<script>
    $(document).ready(function () {
        $("#{{active_page}}").addClass("active");
    })
</script>

{% block extra_js %}
{% endblock %}
</body>
</html>

app/templates/form-errors.html
{% if form.errors is defined %}
    {% for field, errors in form.errors.items() %}
        <div class="alert alert-error">
            <small><strong>{{ form[field].label.text }}</strong>: {{ ', '.join(errors) }}</small>
        </div>
    {% endfor %}
{% endif %}

app/templates/form-macros.html
{# Renders field for bootstrap 3 standards.

    Params:
        field - WTForm field
        kwargs - pass any arguments you want in order to put them into the html attributes.
        There are few exceptions: for - for_, class - class_, class__ - class_

    Example usage:
        {{ macros.render_field(form.email, placeholder='Input email', type='email') }}
#}
{% macro render_field(field, label_visible=true, glyphicon=None, inline_errors=False, show_help=False) -%}

    <div class="form-group {% if field.errors %}has-error{% endif %} {{ kwargs.pop('class_', '') }}">
        {% if (field.type != 'HiddenField' and field.type !='CSRFTokenField') and label_visible %}
            <label for="{{ field.id }}" class="control-label">{{ field.label }}</label>
        {% endif %}
        {% if glyphicon %}
            <div class="input-group">
            <span class="input-group-addon">
                <span class="glyphicon glyphicon-{{ glyphicon }}"></span>
            </span>
        {% endif %}
        {{ field(class_='form-control', **kwargs) }}
        {% if field.description and show_help == True %}
            <span class="help-block">{{ field.description }}</span>
        {% endif %}
        {% if field.errors and inline_errors %}
            {% for e in field.errors %}
                <p class="help-block">{{ e }}</p>
            {% endfor %}
        {% endif %}
        {% if glyphicon %}
        </div>
        {% endif %}
    </div>
{%- endmacro %}

{# Renders checkbox fields since they are represented differently in bootstrap
    Params:
        field - WTForm field (there are no check, but you should put here only BooleanField.
        kwargs - pass any arguments you want in order to put them into the html attributes.
        There are few exceptions: for - for_, class - class_, class__ - class_

    Example usage:
        {{ macros.render_checkbox_field(form.remember_me) }}
 #}
{% macro render_checkbox_field(field) -%}
    <div class="checkbox">
        <label>
            {{ field(type='checkbox', **kwargs) }} {{ field.label }}
        </label>
    </div>
{%- endmacro %}

{# Renders radio field
    Params:
        field - WTForm field (there are no check, but you should put here only BooleanField.
        kwargs - pass any arguments you want in order to put them into the html attributes.
        There are few exceptions: for - for_, class - class_, class__ - class_

    Example usage:
        {{ macros.render_radio_field(form.answers) }}
 #}
{% macro render_radio_field(field) -%}
    {% for value, label, _ in field.iter_choices() %}
        <div class="radio">
            <label>
                <input type="radio" name="{{ field.id }}" id="{{ field.id }}" value="{{ value }}">{{ label }}
            </label>
        </div>
    {% endfor %}
{%- endmacro %}

{# Renders WTForm in bootstrap way. There are two ways to call function:
     - as macros: it will render all field forms using cycle to iterate over them
     - as call: it will insert form fields as you specify:
     e.g. {% call macros.render_form(form, action_url=url_for('login_view'), action_text='Login',
                                        class_='login-form') %}
                {{ macros.render_field(form.email, placeholder='Input email', type='email') }}
                {{ macros.render_field(form.password, placeholder='Input password', type='password') }}
                {{ macros.render_checkbox_field(form.remember_me, type='checkbox') }}
            {% endcall %}

     Params:
        form - WTForm class
        action_url - url where to submit this form
        action_text - text of submit button
        class_ - sets a class for form
    #}
{% macro render_form(form, action_url='', method="POST", action_text='Submit', class_='', btn_class='btn btn-default') -%}

    <form method="{{ method }}" action="{{ action_url }}" role="form" class="{{ class_ }}">
        {{ form.csrf_token }}
        {% if caller %}
            {{ caller() }}
        {% else %}
            {% for f in form %}
                {% if f.type == 'BooleanField' %}
                    {{ render_checkbox_field(f) }}
                {% elif f.type == 'RadioField' %}
                    {{ render_radio_field(f) }}
                {% else %}
                    {{ render_field(f) }}
                {% endif %}
            {% endfor %}
        {% endif %}

        {% if xsrf_token %}
            {{ xsrf_form_html()|safe }}
        {% endif %}

        <button type="submit" class="{{ btn_class }}">{{ action_text }} </button>
    </form>
{%- endmacro %}

app/templates/messages.html
{% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
        {% for category, message in messages %}
            <div class="alert alert-{{ category }}">{{ message }}</div>
        {% endfor %}
    {% endif %}
{% endwith %}

app/templates/pagination.html
{% macro render_pagination(pagination, endpoint, ep_kwargs={}) %}
    {% if pagination.pages > 1 %}
        <div class="row">
            <div class=pagination>
                <div class="btn-toolbar">
                    <div class="btn-group">
                        {%- for page in pagination.iter_pages() %}
                            {% if page %}
                                {% if page != pagination.page %}
                                    <a class="btn btn-default" href="{{ url_for(endpoint, page=page, **ep_kwargs) }}">{{ page }}</a>
                                {% else %}
                                    <a class="btn btn-default active" href="{{ url_for(endpoint, page=page, **ep_kwargs) }}">{{ page }}</a>
                                {% endif %}
                            {% else %}
                                <a class="btn btn-default disabled" href="#">...</a>
                            {% endif %}
                        {%- endfor %}
                    </div>
                </div>
            </div>
        </div>
    {% endif %}
{% endmacro %}